# Generated by Django 4.2.7 on 2023-11-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('auth_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_preference', models.CharField(choices=[('shared', 'Shared Ride'), ('individual', 'Individual Ride')], max_length=20)),
                ('gender_preference', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any Gender')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField()),
                ('filled_capacity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_offered', to='route_scheduler.customuser')),
                ('passengers', models.ManyToManyField(blank=True, null=True, related_name='rides_taken', to='route_scheduler.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_recurring', models.BooleanField(blank=True, default=False, null=True)),
                ('user_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='route_scheduler.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='route_scheduler.customuser')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='route_scheduler.ride')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='route_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='route_scheduler.routeplan'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('reviews', models.TextField()),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='route_scheduler.customuser')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='route_scheduler.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='route_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route_scheduler.routeplan'),
        ),
        migrations.CreateModel(
            name='CostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('driver_share', models.FloatField()),
                ('passenger_share', models.FloatField()),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_share', to='route_scheduler.ride')),
            ],
        ),
    ]
