# Generated by Django 4.2.7 on 2023-11-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vehicle_preference',
            field=models.CharField(blank=True, choices=[('shared', 'Shared Ride'), ('individual', 'Individual Ride')], max_length=20, null=True),
        ),
    ]
