# Generated by Django 4.2.7 on 2023-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, related_name='rides_taken', to='route_scheduler.customuser'),
        ),
    ]
