# Generated by Django 4.2.7 on 2023-11-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeplan',
            name='price',
        ),
    ]
