# Generated by Django 4.2.7 on 2023-11-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_scheduler', '0002_alter_customuser_vehicle_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='route_array',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehicle_preference',
            field=models.CharField(choices=[('shared', 'Shared Ride'), ('individual', 'Individual Ride')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
